// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkwcvZLRCO5aaGZ80gTRe1AZ9I6DDAsbI',
    appId: '1:540722641764:web:d49cbbd3a8673a4d015871',
    messagingSenderId: '540722641764',
    projectId: 'unblockr-625fc',
    authDomain: 'unblockr-625fc.firebaseapp.com',
    storageBucket: 'unblockr-625fc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD11_UcoRU21MGhkmqGnMUcmCdNds0ZgFk',
    appId: '1:540722641764:android:33eb87635cb15462015871',
    messagingSenderId: '540722641764',
    projectId: 'unblockr-625fc',
    storageBucket: 'unblockr-625fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHlym974fW2-79OdTRuzSzrRpyRxxahwk',
    appId: '1:540722641764:ios:31d092fa0c03368d015871',
    messagingSenderId: '540722641764',
    projectId: 'unblockr-625fc',
    storageBucket: 'unblockr-625fc.firebasestorage.app',
    iosBundleId: 'com.smartunblocker.app.smartUnblocker',
  );
}
