import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:provider/provider.dart';

import 'package:firebase_core/firebase_core.dart'; // 🔥 NEW
import 'firebase_options.dart'; // 🔥 NEW (generated by flutterfire)

import 'package:unblockr/screens/splash/splash_screen.dart';
import 'package:unblockr/providers/vehicle_provider.dart';
import 'package:unblockr/providers/settings_provider.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  /// 🔥 Initialize Firebase (FIRST)
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  /// 🔥 Initialize Hive
  await Hive.initFlutter();

  /// 🔥 Open required boxes
  await Hive.openBox('vehicles');
  await Hive.openBox('settings');

  runApp(const UnblockrApp());
}

class UnblockrApp extends StatelessWidget {
  const UnblockrApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(
          create: (_) => VehicleProvider(),
        ),
        ChangeNotifierProvider(
          create: (_) => SettingsProvider(),
        ),
      ],
      child: Consumer<SettingsProvider>(
        builder: (context, settings, _) {
          return MaterialApp(
            title: 'Unblockr',
            debugShowCheckedModeBanner: false,

            theme: ThemeData(
              useMaterial3: true,
              textTheme: GoogleFonts.interTextTheme(),
              scaffoldBackgroundColor: const Color(0xFFEAF3FF),
              brightness: Brightness.light,
            ),

            darkTheme: ThemeData(
              useMaterial3: true,
              textTheme: GoogleFonts.interTextTheme(),
              brightness: Brightness.dark,
            ),

            themeMode:
            settings.darkMode ? ThemeMode.dark : ThemeMode.light,

            home: const SplashScreen(),
          );
        },
      ),
    );
  }
}